# Generated by Django 5.0.4 on 2025-02-04 08:12

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNo', models.CharField(max_length=20)),
                ('insuranceValidity', models.DateField()),
                ('pollutionValidity', models.DateField()),
                ('fitnessValidity', models.DateField()),
                ('vehiclePic', models.ImageField(upload_to='vehiclePics/')),
            ],
        ),
        migrations.CreateModel(
            name='DLInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlNo', models.CharField(max_length=20)),
                ('dlIssueDate', models.DateField()),
                ('dlExpiry', models.DateField()),
                ('dlPic', models.ImageField(upload_to='dlPics/')),
                ('dlFrontPic', models.ImageField(upload_to='dlPics/')),
                ('dlBackPic', models.ImageField(upload_to='dlPics/')),
                ('dlUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=10)),
                ('profilePic', models.ImageField(upload_to='profilePics/')),
                ('Dlinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.dlinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courceName', models.CharField(max_length=50)),
                ('courceDuration', models.DurationField()),
                ('courceFee', models.IntegerField()),
                ('courceInstructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.instructor')),
                ('courceVehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationNo', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=10)),
                ('Dlinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.dlinfo')),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.cource')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.instructor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('timeIn', models.TimeField(default=datetime.time(0, 0))),
                ('timeOut', models.TimeField(default=datetime.time(0, 0))),
                ('qr_code_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.student')),
            ],
        ),
    ]
