# Generated by Django 5.0.4 on 2025-02-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=50)),
                ('branchAddress', models.TextField()),
                ('branchPhoneNo', models.CharField(max_length=10)),
                ('branchEmail', models.EmailField(max_length=254)),
                ('branchIncharge', models.CharField(max_length=50)),
                ('branchInchargePhoneNo', models.CharField(max_length=10)),
                ('branchInchargeEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='cource',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.branch'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.branch'),
        ),
    ]
