# Generated by Django 5.0.4 on 2025-02-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_branch_cource_branch_instructor_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlinfo',
            name='dlBackPic',
        ),
        migrations.RemoveField(
            model_name='dlinfo',
            name='dlFrontPic',
        ),
    ]
