# Generated by Django 5.0.4 on 2025-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_remove_dlinfo_dlbackpic_remove_dlinfo_dlfrontpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='bloodGroup',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
