# Generated by Django 5.0.4 on 2025-02-06 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_instructor_bloodgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branchInchargeEmail',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branchInchargePhoneNo',
        ),
        migrations.AlterField(
            model_name='branch',
            name='branchIncharge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
