# Generated by Django 5.0.4 on 2025-02-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0005_remove_branch_branchinchargeemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicalName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
