# Generated by Django 5.0.4 on 2025-02-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0006_vehicle_vehicalname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehiclePic',
        ),
    ]
