# Generated by Django 5.0.4 on 2025-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0007_remove_vehicle_vehiclepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleNo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
