# Generated by Django 5.0.4 on 2025-02-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0008_alter_vehicle_vehicleno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlinfo',
            name='dlPic',
        ),
    ]
