# Generated by Django 5.0.4 on 2025-02-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0009_remove_dlinfo_dlpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profilePics/'),
        ),
    ]
