# Generated by Django 5.0.4 on 2025-02-10 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0010_alter_instructor_profilepic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branchIncharge',
        ),
        migrations.AddField(
            model_name='branch',
            name='branchIncharge',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
