# Generated by Django 5.0.4 on 2025-02-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0012_remove_branch_branchincharge_branch_branchincharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicalType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
