# Generated by Django 5.0.4 on 2025-02-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0013_vehicle_vehicaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='courceDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
