# Generated by Django 5.0.4 on 2025-02-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0014_cource_courcedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='courceDuration',
            field=models.IntegerField(),
        ),
    ]
