# Generated by Django 5.0.4 on 2025-02-24 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0015_alter_cource_courceduration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='Dlinfo',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='bloodGroup',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='phoneNo',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='profilePic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bloodGroup',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phoneNo',
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructorBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.branch'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructorVehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.vehicle'),
        ),
        migrations.AddField(
            model_name='student',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.branch'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotName', models.CharField(max_length=50)),
                ('slotStart', models.TimeField()),
                ('slotEnd', models.TimeField()),
                ('slotBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.branch')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='AdminPanel.slot'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=10)),
                ('bloodGroup', models.CharField(blank=True, max_length=5, null=True)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profilePics/')),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_branchAdmin', models.BooleanField(default=False)),
                ('is_superAdmin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='dlinfo',
            name='dlUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.userprofile'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='AdminPanel.userprofile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.userprofile'),
        ),
    ]
