# Generated by Django 5.0.4 on 2025-02-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0016_remove_instructor_dlinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slot',
        ),
    ]
