# Generated by Django 5.0.4 on 2025-02-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0017_remove_student_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
