# Generated by Django 5.0.4 on 2025-02-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0018_delete_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotName', models.CharField(max_length=50)),
                ('slotStart', models.TimeField()),
                ('slotEnd', models.TimeField()),
                ('slotBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.branch')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='AdminPanel.slot'),
        ),
    ]
