# Generated by Django 5.0.4 on 2025-02-24 11:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0019_slot_student_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branchIncharge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.userprofile'),
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainDescription', models.TextField()),
                ('complainDate', models.DateField()),
                ('complainTime', models.TimeField(default=datetime.time(0, 0))),
                ('complainStatus', models.CharField(max_length=50)),
                ('compalainFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.userprofile')),
                ('complainBranch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.branch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentDescription', models.TextField()),
                ('contentType', models.CharField(max_length=50)),
                ('contentVideo', models.FileField(blank=True, null=True, upload_to='courceContent/')),
                ('contentFile', models.FileField(blank=True, null=True, upload_to='courceContent/')),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.cource')),
            ],
        ),
    ]
