# Generated by Django 5.0.4 on 2025-02-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0020_alter_branch_branchincharge_complain_courcecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicalName',
            new_name='vehicleName',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicalType',
            new_name='vehicleType',
        ),
    ]
