# Generated by Django 5.0.4 on 2025-02-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0021_rename_vehicalname_vehicle_vehiclename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cource',
            name='courceVehicle',
        ),
    ]
