# Generated by Django 5.0.4 on 2025-02-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0022_remove_cource_courcevehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='complainStatus',
        ),
        migrations.AddField(
            model_name='complain',
            name='complainResolved',
            field=models.BooleanField(default=False),
        ),
    ]
