# Generated by Django 5.0.4 on 2025-02-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0023_remove_complain_complainstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='compalainTitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
