# Generated by Django 5.0.4 on 2025-02-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0024_complain_compalaintitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='student',
        ),
    ]
