# Generated by Django 5.0.4 on 2025-02-25 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0025_remove_complain_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='compalainForm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.student'),
        ),
    ]
