# Generated by Django 4.2.5 on 2025-02-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0026_complain_compalainform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courcecontent',
            name='cource',
        ),
    ]
