# Generated by Django 4.2.5 on 2025-02-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0027_remove_courcecontent_cource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courcecontent',
            name='contentType',
        ),
    ]
