# Generated by Django 5.0.4 on 2025-02-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0028_remove_courcecontent_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courceEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='courceEnrollDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='courceStatus',
            field=models.BooleanField(default=False),
        ),
    ]
