# Generated by Django 5.0.4 on 2025-02-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0029_student_courceenddate_student_courceenrolldate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
