# Generated by Django 5.0.4 on 2025-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0032_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amountPaid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='amountPending',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
