# Generated by Django 5.0.4 on 2025-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0033_student_amountpaid_student_amountpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paymentDueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
