# Generated by Django 5.0.4 on 2025-03-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0034_student_paymentduedate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
