# Generated by Django 5.0.4 on 2025-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0035_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlinfo',
            name='dlType',
            field=models.CharField(blank=True, choices=[('Learning License', 'Learning License'), ('Driving License', 'Driving License')], max_length=20, null=True),
        ),
    ]
