# Generated by Django 5.0.4 on 2025-03-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0036_dlinfo_dltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Dlinfo',
        ),
    ]
