# Generated by Django 5.0.4 on 2025-03-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0037_remove_student_dlinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amountPaid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='amountPending',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
