# Generated by Django 5.0.4 on 2025-03-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0038_alter_student_amountpaid_alter_student_amountpending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField()),
                ('paymentAmount', models.IntegerField()),
                ('paymentMethod', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.student')),
            ],
        ),
    ]
