# Generated by Django 5.0.4 on 2025-03-12 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0039_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentRecevedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.userprofile'),
        ),
    ]
