# Generated by Django 5.0.4 on 2025-03-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0040_payment_paymentrecevedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attened_session',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_session',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
