# Generated by Django 5.0.4 on 2025-03-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0041_student_attened_session_student_total_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='total_session',
        ),
        migrations.AddField(
            model_name='cource',
            name='total_session',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
