# Generated by Django 5.0.4 on 2025-03-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0042_remove_student_total_session_cource_total_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slotUsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_staus',
            field=models.BooleanField(default=False),
        ),
    ]
