# Generated by Django 5.0.4 on 2025-03-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0043_slot_slotused_student_student_staus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='booking_Type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
