# Generated by Django 5.0.4 on 2025-03-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0044_student_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slotPreBooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_staus',
            field=models.BooleanField(default=True),
        ),
    ]
