# Generated by Django 5.0.4 on 2025-03-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0045_slot_slotprebooked_alter_student_student_staus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=50)),
                ('serviceFee', models.IntegerField()),
                ('mandetory', models.BooleanField(default=False)),
            ],
        ),
    ]
