# Generated by Django 4.2.5 on 2025-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0046_addonservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addOnService',
            field=models.ManyToManyField(blank=True, null=True, to='AdminPanel.addonservice'),
        ),
    ]
