# Generated by Django 4.2.5 on 2025-03-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0047_student_addonservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='addOnService',
            field=models.ManyToManyField(to='AdminPanel.addonservice'),
        ),
    ]
