# Generated by Django 4.2.5 on 2025-03-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0048_alter_student_addonservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='adharCard',
            field=models.FileField(blank=True, null=True, upload_to='instructorDoc/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='aggreementDoc',
            field=models.FileField(blank=True, null=True, upload_to='instructorDoc/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='policeVerificationDoc',
            field=models.FileField(blank=True, null=True, upload_to='instructorDoc/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AdminPanel.student'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='courceInstructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AdminPanel.instructor'),
        ),
    ]
