# Generated by Django 4.2.5 on 2025-03-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0049_instructor_adharcard_instructor_aggreementdoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
