# Generated by Django 4.2.5 on 2025-03-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0050_instructor_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.student'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='courceInstructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.instructor'),
        ),
    ]
