# Generated by Django 5.0.4 on 2025-05-14 08:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0051_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationTitle', models.CharField(max_length=100)),
                ('notificationDescription', models.TextField()),
                ('notificationDate', models.DateField()),
                ('notificationTime', models.TimeField(default=datetime.time(0, 0))),
                ('notificationBranch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.branch')),
            ],
        ),
    ]
