# Generated by Django 5.0.4 on 2025-05-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0052_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notificationDescription',
        ),
    ]
