# Generated by Django 5.0.4 on 2025-05-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0053_remove_notification_notificationdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notificationIsRead',
            field=models.BooleanField(default=False),
        ),
    ]
