# Generated by Django 5.0.4 on 2025-05-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0054_notification_notificationisread'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('slotStart', 'slotEnd', 'slotBranch')},
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slotName',
        ),
    ]
