# Generated by Django 5.0.4 on 2025-05-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0056_addonservice_is_active_attendance_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicleBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.branch'),
        ),
    ]
