# Generated by Django 5.0.4 on 2025-05-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0057_vehicle_vehiclebranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cource',
            name='courceInstructor',
        ),
        migrations.AddField(
            model_name='cource',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.vehicle'),
        ),
    ]
