# Generated by Django 5.0.4 on 2025-05-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0058_remove_cource_courceinstructor_cource_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructorVehicle',
        ),
    ]
