# Generated by Django 5.0.4 on 2025-05-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0059_remove_instructor_instructorvehicle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('vehicle', 'slotStart', 'slotEnd', 'slotBranch')},
        ),
    ]
