# Generated by Django 5.0.4 on 2025-08-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0060_alter_slot_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='qr_code_uuid',
        ),
    ]
