# Generated by Django 5.0.4 on 2025-08-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0061_remove_attendance_qr_code_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qrCodeData',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
