# Generated by Django 5.0.4 on 2025-08-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0062_vehicle_qrcodedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qrCodeImage',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_qrcodes/'),
        ),
    ]
