# Generated by Django 4.2.24 on 2025-10-11 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0063_vehicle_qrcodeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='resolved_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 10, 12, 0, 31, 5, 756495), null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to='AdminPanel.userprofile'),
        ),
    ]
