# Generated by Django 4.2.24 on 2025-10-11 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0064_complain_action_taken_complain_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='resolved_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 12, 0, 31, 47, 481694), null=True),
        ),
    ]
