# Generated by Django 4.2.24 on 2025-10-11 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0065_alter_complain_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='resolved_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 12, 0, 32, 20, 763327), null=True),
        ),
    ]
