# Generated by Django 4.2.24 on 2025-10-11 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0067_remove_attendance_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='complainDate',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='complainTime',
        ),
        migrations.AlterField(
            model_name='complain',
            name='resolved_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 12, 0, 58, 46, 268366), null=True),
        ),
    ]
