# Generated by Django 4.2.24 on 2025-10-17 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0069_attendance_created_by_alter_complain_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='resolved_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 17, 22, 15, 56, 391321), null=True),
        ),
        migrations.CreateModel(
            name='StudentCouseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courceEnrollDate', models.DateField()),
                ('courceCompletionDate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.cource')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.userprofile')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.student')),
            ],
        ),
    ]
