# Generated by Django 4.2.24 on 2025-10-23 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0070_alter_complain_resolved_at_studentcousehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='resolved_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 23, 21, 40, 45, 377813), null=True),
        ),
    ]
