# Generated by Django 4.2.24 on 2025-11-03 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0071_attendance_is_active_attendance_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='resolved_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 3, 22, 31, 11, 111773), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='applicationNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
